### ISSUE TITLE
Home page Background image is not rendered in a 100% width

### ISSUE THREAD

**Issue by gastaldi** [forge/website#19]
![](http://i.imgur.com/AjFkhrz.png)

**Comment by lincolnthree** [comment]
This is another issue that might be related - see video: https://www.youtube.com/watch?v=FYcHE_G7g6I&feature=youtu.be

**Comment by gastaldi** [comment]
Reproducible in a 770 x 600 screen

**Comment by visuale** [comment]
I'm still trying to get this working right. In the meantime, am pushing up a version where it's just the static, non-parallax sparks image for the background of that section.
