### ISSUE TITLE
Whenever I open a tutorial on the new website, I have to scroll up to be able to read from the beginning

### ISSUE THREAD

**Issue by gastaldi** [forge/website#20]
Reported by @addonis1990: whenever I open a tutorial on the new website, I have to scroll up to be able to read from the beginning

**Comment by gastaldi** [comment]
To reproduce that, go to http://forge.jboss.org/documentation then scroll to the bottom of the page and click on "Share your Addon on the Forge website" for example

**Comment by addonis1990** [comment]
@gastaldi  the top bar is still missing from most pages, again you have to scroll up to see it  (using Firefox 38)

**Comment by gastaldi** [comment]
Yes, I noticed that also. I'll reopen this issue until we find a better solution
