### ISSUE TITLE
Request adding forge as sdkman vendor

### ISSUE THREAD

**Issue by warrenc5** [forge/website#25]
I'm just a newbie checking out forge for the first time, my first thought was to install the latest forge release  with sdkman.io.
I checked - it wasn't on their list. 
I would get it using sdkman if it were available as I am lazy dev - that's why I'm interested in Forge :)

[vendor link to sdkman](https://sdkman.io/vendors)

https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process

**Comment by gastaldi** [comment]
Forge is already available in Homebrew. You can install it with: 

`brew install jboss-forge`

**Comment by warrenc5** [comment]
Why use Homebrew package manager on Linux when you have got apt, dnf, snap etc?

I know the feeling. You already have a good [package manager](https://itsfoss.com/package-manager/) provided by your distribution. In addition to that, you have Snap, Flatpak and other universal package system.

Do you really need Homebrew package manager on your Linux system? The answer depends on your requirement, really.

**Comment by gastaldi** [comment]
When JBoss Forge is used inside the IDEs through their respective plug-ins, a package manager isn't relevant anymore. I'd recommend installing the Forge plug-in in your favorite IDE instead (Eclipse or IntelliJ IDEA - Netbeans is a community effort and isn't maintained for some time now but it might still work)

**Comment by warrenc5** [comment]
Yes, I agree,  I use and love Netbeans, but the plugins link http://plugins.netbeans.org/plugin/57296/ page didn't show up.. from the page https://forge.jboss.org/download and I can't seem to find forge plugin in https://plugins.netbeans.apache.org/?search=forge&nbv=&cat=

Maybe that's my actual problem :)  I'm trying to build and install the netbeans plugin now.

That's why I fell back to sdkman and now I have installed brew and forge. 
Ta.

**Comment by gastaldi** [comment]
> Yes, I agree, I use and love Netbeans, but the plugins link [http://plugins.netbeans.org/plugin/57296](http://plugins.netbeans.org/plugin/57296/) page didn't show up.. from the page [forge.jboss.org/download](https://forge.jboss.org/download) and I can't seem to find forge plugin in [plugins.netbeans.apache.org/?search=forge&nbv=&cat=](https://plugins.netbeans.apache.org/?search=forge&nbv=&cat=)
> 
> Maybe that's my actual problem :) I'm trying to build and install the netbeans plugin now.

You're in luck! I created https://github.com/forge/netbeans-plugin/pull/2 which contains the updates to NetBeans 13 (tests still failing but the build passes - build it with `mvn clean install -DskipTests`).

**Comment by gastaldi** [comment]
I placed the instructions here: https://github.com/forge/netbeans-plugin/pull/2#issuecomment-1113901470. I'll move it once I get familiarized with the Plugin Portal

I'm closing this issue now. Thanks for the feedback!
